---
- hosts: odoo
  remote_user: gnupyx
  become: yes
  tasks:
    - name: Update a server
      apt: update_cache=yes

    - name: Add default packages
      apt: name=ca-certificates state=present

    - name: Add repository signing key
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: Add Postgresql repository
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present update_cache=yes

    - name: Install Postgresql 9.5
      apt: name=postgresql-9.5 state=present

    - name: Install Psycopg2
      apt: name=python-psycopg2 state=present

    - name: Start Postgresql
      apt: name=postgresql state=present

    - name: PostgreSQL | Extensions | Make sure the postgres contrib extensions are installed | Debian
      apt:
        name: "postgresql-contrib-9.5"
        state: present
        update_cache: yes
        cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
      notify:
        - restart postgresql

    - name: PostgreSQL | Extensions | Make sure the development headers are installed
      apt:
        name: libpq-dev
        state: present
        update_cache: yes
        cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
      notify:
        - restart postgresql

    - name: PostgreSQL | Ensure PostgreSQL is running
      service:
        name: "postgresql"
        state: started

    handlers:
      - name: restart postgresql
        service: name=postgresql state=restarted
